services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - ./.env.db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app

  mailhog:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app

networks:
  app:
